<?php
require('classDB.php');
require('classColor.php');
require('classCategory.php');
require('classProducts.php');
require('classImage.php');
require('classAdminLogin.php');
require('classCustomer.php');
require('classDataWash.php');
require('classOrder.php');